### ISSUE TITLE
Is there a wrapper for c# planned?

### ISSUE THREAD

**Issue by AndreasSchmid1** [firebase/quickstart-cpp#25]
C# is a big framework and many people are requesting a sdk. after you dont have a c# sdk maybe it is worth to provide a wrapper for your c++sdk

**Comment by stewartmiles** [comment]
We have C# bindings for Unity https://firebase.google.com/docs/unity/setup is that what you're after or do you have a different environment you're integrating with?

We have an internal build that supports use of the C# API surface from vanilla Mono as well (basically we swap out the Firebase.Platform.dll to one that doesn't use Unity APIs), is that what you're after?

**Comment by AndreasSchmid1** [comment]
Hi stewartmiles. Thanks for the fast reply. 
No I am working on a Angular SPA with asp.net backend. I have also Wpf apps who want to auth to the asp.net backend. Currently I am working with the firebase-database-dotnet nuget third party package.

**Comment by stewartmiles** [comment]
@AndreasSchmid1 we provide two different styles of SDKs for Firebase.  Our C++ and Unity / C# SDKs are client side SDKs, Firebase also publishes server side SDKs that are intended for use from your backend since the auth mechanism and caching requirements are pretty different.  I don't think our client side SDKs are what you're after, I recommend taking a look at our server / admin SDKs https://firebase.google.com/docs/admin/setup which will require some work to plumb into your asp.net backend.

**Comment by stewartmiles** [comment]
@AndreasSchmid1 I'm closing this out as we haven't heard from you, I'll assume your question is answered.
